"""Build dual_encoder_divergence.ipynb"""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

def md(src, cell_id):
    return {"cell_type": "markdown", "id": cell_id, "metadata": {}, "source": src}

def code(src, cell_id):
    return {"cell_type": "code", "execution_count": None, "id": cell_id,
            "metadata": {}, "outputs": [], "source": src}

cells = []

# Cell 0 – title
cells.append(md(
    "# Dual Language-Specific Encoder Pairs — Adversarial Divergence Experiment\n"
    "\n"
    "**Goal:** Break cross-lingual adversarial transfer by giving each language its own\n"
    "encoder pair: per-language LoRA adapters inside every ViT block (image side) plus\n"
    "per-language text projection heads (text side), trained with a three-term loss:\n"
    "\n"
    "```\n"
    "L = sum_l  CE(f_l(x) . g_l^T, y)                   (1) classification\n"
    "  + lam_div  sum_{l!=l'} cos(f_l(x), f_{l'}(x))    (2) image divergence\n"
    "  + lam_ret  sum_{l!=en} CE(f_l(x_adv) . g_l^T, y) (3) adversarial retention\n"
    "```\n"
    "\n"
    "**Key difference from prior experiments (A-F):** both image AND text sides are\n"
    "language-specific simultaneously. Classification and divergence losses now reinforce\n"
    "each other instead of fighting (shared text anchors previously re-centered images).\n"
    "\n"
    "**Success criterion:** retention > 50% in at least 1 non-EN language at any epsilon.",
    "cell-title"))

# Cell 1 – install
cells.append(code(
    "import subprocess, sys\n"
    "\n"
    "subprocess.check_call([\n"
    "    sys.executable, \"-m\", \"pip\", \"install\", \"-q\",\n"
    "    \"open_clip_torch\", \"transformers\", \"datasets\", \"ftfy\", \"sentencepiece\",\n"
    "])\n"
    "print(\"packages installed into:\", sys.executable)",
    "cell-install"))

# Cell 2 – imports
cells.append(code(
    "import importlib, sys\n"
    "\n"
    "import transformers  # must import BEFORE open_clip\n"
    "print(\"transformers\", transformers.__version__)\n"
    "\n"
    "if \"open_clip\" in sys.modules:\n"
    "    import open_clip.hf_model as _oc_hf\n"
    "    if _oc_hf.transformers is None:\n"
    "        for name in list(sys.modules):\n"
    "            if name == \"open_clip\" or name.startswith(\"open_clip.\"):\n"
    "                del sys.modules[name]\n"
    "        importlib.invalidate_caches()\n"
    "\n"
    "import torch, torch.nn as nn, torch.nn.functional as F\n"
    "import numpy as np, time\n"
    "import torchvision, torchvision.transforms as T\n"
    "from torch.utils.data import DataLoader, Subset\n"
    "import open_clip\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "import open_clip.hf_model as _oc_hf\n"
    "assert _oc_hf.transformers is not None, \"restart kernel and re-run from top\"\n"
    "\n"
    "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n"
    "assert device == \"cuda\", \"Enable a GPU runtime\"\n"
    "print(\"device:\", torch.cuda.get_device_name(0))\n"
    "torch.manual_seed(0); np.random.seed(0)",
    "cell-imports"))

# Cell 3 – constants
cells.append(code(
    "DATASET      = \"cifar10\"\n"
    "N_CLEAN      = 500\n"
    "N_TRANSFER   = 300\n"
    "EPS_LIST     = [0.5, 1, 2, 4, 8]\n"
    "PGD_STEPS    = 20\n"
    "BATCH        = 64\n"
    "LANGS        = [\"en\", \"ko\", \"es\", \"fr\", \"ja\"]\n"
    "\n"
    "# Dual-encoder hyperparameters\n"
    "RANK           = 32       # LoRA rank (Exp C used 16 and collapsed at LR=1e-3)\n"
    "LAM_DIV        = 1.0      # image-embedding divergence weight\n"
    "LAM_RET        = 1.0      # adversarial retention weight\n"
    "DUAL_LR        = 1e-4     # 10x lower than Exp C -- prevents collapse\n"
    "DUAL_EPOCHS    = 15\n"
    "DUAL_TRAIN_N   = 1000\n"
    "DUAL_PGD_STEPS = 7        # fast inner loop\n"
    "DUAL_TRAIN_EPS = 2 / 255  # training attack budget\n"
    "\n"
    "print(\"config OK | dataset:\", DATASET, \"| rank:\", RANK, \"| lr:\", DUAL_LR)",
    "cell-constants"))

# Cell 4 – model
cells.append(code(
    "model, _, preprocess_val = open_clip.create_model_and_transforms(\n"
    "    \"xlm-roberta-base-ViT-B-32\", pretrained=\"laion5b_s13b_b90k\")\n"
    "tokenizer = open_clip.get_tokenizer(\"xlm-roberta-base-ViT-B-32\")\n"
    "model = model.to(device).eval()\n"
    "for p in model.parameters(): p.requires_grad_(False)\n"
    "\n"
    "norm = [t for t in preprocess_val.transforms if isinstance(t, T.Normalize)][0]\n"
    "MEAN = torch.tensor(norm.mean, device=device).view(1, 3, 1, 1)\n"
    "STD  = torch.tensor(norm.std,  device=device).view(1, 3, 1, 1)\n"
    "LOGIT_SCALE = model.logit_scale.exp().detach()\n"
    "\n"
    "def encode_image(x_pixel):\n"
    "    feats = model.encode_image((x_pixel - MEAN) / STD)\n"
    "    return F.normalize(feats, dim=-1)\n"
    "\n"
    "def logits_for(img_feats, txt_feats):\n"
    "    return LOGIT_SCALE * img_feats @ txt_feats.t()\n"
    "\n"
    "print(\"model loaded; logit_scale =\", float(LOGIT_SCALE))",
    "cell-model"))

# Cell 5 – translations
cells.append(code(
    "CIFAR10_CLASSES = [\"airplane\",\"automobile\",\"bird\",\"cat\",\"deer\",\n"
    "                   \"dog\",\"frog\",\"horse\",\"ship\",\"truck\"]\n"
    "STL10_CLASSES   = [\"airplane\",\"bird\",\"car\",\"cat\",\"deer\",\n"
    "                   \"dog\",\"horse\",\"monkey\",\"ship\",\"truck\"]\n"
    "\n"
    "TRANSLATIONS = {\n"
    " \"airplane\":  {\"en\":\"airplane\",\"ko\":\"\ube44\ud589\uae30\",\"es\":\"avi\u00f3n\",\"fr\":\"avion\",\"ja\":\"\u98db\u884c\u6a5f\"},\n"
    " \"automobile\":{\"en\":\"automobile\",\"ko\":\"\uc790\ub3d9\ucc28\",\"es\":\"autom\u00f3vil\",\"fr\":\"automobile\",\"ja\":\"\u81ea\u52d5\u8eca\"},\n"
    " \"car\":       {\"en\":\"car\",\"ko\":\"\uc790\ub3d9\ucc28\",\"es\":\"coche\",\"fr\":\"voiture\",\"ja\":\"\u8eca\"},\n"
    " \"bird\":      {\"en\":\"bird\",\"ko\":\"\uc0c8\",\"es\":\"p\u00e1jaro\",\"fr\":\"oiseau\",\"ja\":\"\u9ce5\"},\n"
    " \"cat\":       {\"en\":\"cat\",\"ko\":\"\uace0\uc591\uc774\",\"es\":\"gato\",\"fr\":\"chat\",\"ja\":\"\u732b\"},\n"
    " \"deer\":      {\"en\":\"deer\",\"ko\":\"\uc0ac\uc2b4\",\"es\":\"ciervo\",\"fr\":\"cerf\",\"ja\":\"\u9e7f\"},\n"
    " \"dog\":       {\"en\":\"dog\",\"ko\":\"\uac1c\",\"es\":\"perro\",\"fr\":\"chien\",\"ja\":\"\u72ac\"},\n"
    " \"frog\":      {\"en\":\"frog\",\"ko\":\"\uac1c\uad6c\ub9ac\",\"es\":\"rana\",\"fr\":\"grenouille\",\"ja\":\"\u30ab\u30a8\u30eb\"},\n"
    " \"horse\":     {\"en\":\"horse\",\"ko\":\"\ub9d0\",\"es\":\"caballo\",\"fr\":\"cheval\",\"ja\":\"\u99ac\"},\n"
    " \"monkey\":    {\"en\":\"monkey\",\"ko\":\"\uc6d0\uc22d\uc774\",\"es\":\"mono\",\"fr\":\"singe\",\"ja\":\"\u733f\"},\n"
    " \"ship\":      {\"en\":\"ship\",\"ko\":\"\ubc30\",\"es\":\"barco\",\"fr\":\"bateau\",\"ja\":\"\u8239\"},\n"
    " \"truck\":     {\"en\":\"truck\",\"ko\":\"\ud2b8\ub7ed\",\"es\":\"cami\u00f3n\",\"fr\":\"camion\",\"ja\":\"\u30c8\u30e9\u30c3\u30af\"},\n"
    "}\n"
    "TEMPLATES = {\n"
    "    \"en\": \"a photo of a {}.\",\n"
    "    \"ko\": \"{}\uc758 \uc0ac\uc9c4.\",\n"
    "    \"es\": \"una foto de un {}.\",\n"
    "    \"fr\": \"une photo d'un {}.\",\n"
    "    \"ja\": \"{}\u306e\u5199\u771f\u3002\"\n"
    "}\n"
    "\n"
    "@torch.no_grad()\n"
    "def build_text_embeddings(classes):\n"
    "    out = {}\n"
    "    for l in LANGS:\n"
    "        prompts = [TEMPLATES[l].format(TRANSLATIONS[c][l]) for c in classes]\n"
    "        feats = model.encode_text(tokenizer(prompts).to(device))\n"
    "        out[l] = F.normalize(feats, dim=-1)\n"
    "    return out\n"
    "\n"
    "print(\"translations + text-embedding builder ready\")",
    "cell-translations"))

# Cell 6 – dataset
cells.append(code(
    "from datasets import load_dataset\n"
    "\n"
    "pixel_tf = T.Compose([T.Resize(224, interpolation=T.InterpolationMode.BICUBIC),\n"
    "                      T.CenterCrop(224), T.ToTensor()])\n"
    "_CIFAR_HF = {}\n"
    "\n"
    "class HFCifar10(torch.utils.data.Dataset):\n"
    "    def __init__(self, hf_ds, transform):\n"
    "        self.hf_ds, self.transform = hf_ds, transform\n"
    "    def __len__(self): return len(self.hf_ds)\n"
    "    def __getitem__(self, i):\n"
    "        ex = self.hf_ds[i]\n"
    "        img = ex[\"img\"]\n"
    "        if self.transform is not None:\n"
    "            img = self.transform(img)\n"
    "        return img, ex[\"label\"]\n"
    "\n"
    "def load_cifar10(split, transform):\n"
    "    if split not in _CIFAR_HF:\n"
    "        hf_split = \"train\" if split == \"train\" else \"test\"\n"
    "        print(f\"Loading CIFAR-10 {split} from HuggingFace...\")\n"
    "        _CIFAR_HF[split] = load_dataset(\"uoft-cs/cifar10\", split=hf_split)\n"
    "    return HFCifar10(_CIFAR_HF[split], transform)\n"
    "\n"
    "NUM_WORKERS = 0 if sys.platform == \"win32\" else 2\n"
    "\n"
    "def get_loader(n, batch_size=BATCH, seed=0, split=\"test\"):\n"
    "    if DATASET == \"stl10\":\n"
    "        tv_split = \"train\" if split == \"train\" else \"test\"\n"
    "        ds = torchvision.datasets.STL10(\"data\", split=tv_split, download=True, transform=pixel_tf)\n"
    "        classes = STL10_CLASSES\n"
    "    else:\n"
    "        ds = load_cifar10(split, pixel_tf)\n"
    "        classes = CIFAR10_CLASSES\n"
    "    if n < len(ds):\n"
    "        idx = np.random.default_rng(seed).permutation(len(ds))[:n]\n"
    "        ds = Subset(ds, idx.tolist())\n"
    "    return DataLoader(ds, batch_size=batch_size, shuffle=False, num_workers=NUM_WORKERS), classes\n"
    "\n"
    "loader, CLASSES = get_loader(N_CLEAN)\n"
    "TXT = build_text_embeddings(CLASSES)\n"
    "print(\"classes:\", CLASSES)",
    "cell-dataset"))

# Cell 7 – architecture
cells.append(code(
    "# ── Image side: per-language CLS-token LoRA at every ViT block ───────────────\n"
    "#\n"
    "# The ViT uses NLD layout [batch, seq, d] with batch_first=True throughout.\n"
    "# CLS token: x[:, 0, :]   Injection: cat([cls_new.unsqueeze(1), x[:, 1:]], dim=1)\n"
    "#\n"
    "# CRITICAL FIX vs. Experiment C: Exp C manually permuted to LND (seq-first)\n"
    "# before passing to resblocks. With batch_first=True the resblocks expect NLD,\n"
    "# so Exp C's attention ran over batch items (seq=2) not tokens (seq=50) --\n"
    "# semantically wrong, which contributed to training collapse.\n"
    "# This implementation uses vit._embeds() which correctly returns NLD.\n"
    "\n"
    "class IntermediateLoRA(nn.Module):\n"
    "    def __init__(self, d=768, r=RANK):\n"
    "        super().__init__()\n"
    "        self.A = nn.Linear(d, r, bias=False)\n"
    "        self.B = nn.Linear(r, d, bias=False)\n"
    "        nn.init.kaiming_uniform_(self.A.weight)\n"
    "        nn.init.zeros_(self.B.weight)  # zero-init B: starts as identity\n"
    "\n"
    "    def forward(self, x):\n"
    "        return x + self.B(self.A(x))\n"
    "\n"
    "# 5 languages x 12 blocks = 60 adapters\n"
    "ml_adapters = nn.ModuleDict({\n"
    "    f\"{lang}_{i}\": IntermediateLoRA(d=768, r=RANK).to(device)\n"
    "    for lang in LANGS for i in range(12)\n"
    "})\n"
    "\n"
    "# ── Text side: per-language projection heads ──────────────────────────────────\n"
    "#\n"
    "# model.text is HFTextEncoder with MeanPooler -> 768-d -> model.text.proj (Sequential)\n"
    "# We bypass model.text.proj entirely and apply our own nn.Linear(768, 512) per lang.\n"
    "# Gradient flows through lang_text_proj[lang]; backbone (XLM-R) stays frozen.\n"
    "\n"
    "lang_text_proj = nn.ModuleDict({\n"
    "    lang: nn.Linear(768, 512, bias=False).to(device)\n"
    "    for lang in LANGS\n"
    "})\n"
    "for proj in lang_text_proj.values():\n"
    "    nn.init.kaiming_uniform_(proj.weight)\n"
    "\n"
    "total_img = sum(p.numel() for p in ml_adapters.parameters())\n"
    "total_txt = sum(p.numel() for p in lang_text_proj.parameters())\n"
    "print(f\"Trainable parameters: {total_img + total_txt:,}  ({(total_img+total_txt)/1e6:.2f}M)\")\n"
    "print(f\"  image LoRA adapters: {total_img:,}  (5 langs x 12 blocks x 2x(768x{RANK}))\")\n"
    "print(f\"  text proj heads:     {total_txt:,}  (5 langs x 768x512)\")\n"
    "print(f\"  frozen backbone:     {sum(p.numel() for p in model.parameters()):,}\")\n"
    "\n"
    "# ── encode_image_ml: ViT forward with per-language CLS injection ──────────────\n"
    "def encode_image_ml(x_pixel, lang):\n"
    "    vit = model.visual\n"
    "    x = vit._embeds((x_pixel - MEAN) / STD)          # [B, 50, 768] NLD\n"
    "    for i, block in enumerate(vit.transformer.resblocks):\n"
    "        x = block(x)                                   # [B, 50, 768]\n"
    "        cls_new = ml_adapters[f\"{lang}_{i}\"](x[:, 0, :])         # [B, 768]\n"
    "        x = torch.cat([cls_new.unsqueeze(1), x[:, 1:, :]], dim=1) # [B, 50, 768]\n"
    "    x = vit.ln_post(x[:, 0, :])   # [B, 768]  pool_type='tok'\n"
    "    if vit.proj is not None:\n"
    "        x = x @ vit.proj           # [B, 512]\n"
    "    return F.normalize(x, dim=-1)\n"
    "\n"
    "# ── encode_text_lang: frozen XLM-R backbone + trainable per-language head ─────\n"
    "# MeanPooler: masked mean of last_hidden_state -> [B, 768]\n"
    "# Backbone runs in no_grad; gradient flows through lang_text_proj[lang] only.\n"
    "def encode_text_lang(prompts, lang):\n"
    "    tokens = tokenizer(prompts).to(device)\n"
    "    attn_mask = (tokens != model.text.config.pad_token_id).long()\n"
    "    with torch.no_grad():\n"
    "        out = model.text.transformer(input_ids=tokens, attention_mask=attn_mask)\n"
    "        masked = out.last_hidden_state * attn_mask.unsqueeze(-1).float()\n"
    "        pooled = masked.sum(dim=1) / attn_mask.sum(-1, keepdim=True).float()  # [B, 768]\n"
    "    projected = lang_text_proj[lang](pooled)  # [B, 512] -- grad flows here\n"
    "    return F.normalize(projected, dim=-1)\n"
    "\n"
    "# ── build_txt_lang: pre-compute text embeddings from cached backbone features ──\n"
    "# txt_backbone is set in the training cell (pre-computed once before training).\n"
    "@torch.no_grad()\n"
    "def build_txt_lang():\n"
    "    return {\n"
    "        lang: F.normalize(lang_text_proj[lang](txt_backbone[lang]), dim=-1)\n"
    "        for lang in LANGS\n"
    "    }\n"
    "\n"
    "# ── Shape check ───────────────────────────────────────────────────────────────\n"
    "with torch.no_grad():\n"
    "    _d, _ = next(iter(get_loader(2, batch_size=2, seed=99)[0]))\n"
    "    _f = encode_image_ml(_d.to(device), \"en\")\n"
    "    print(f\"encode_image_ml output: {_f.shape}  (expected [2, 512])\")\n"
    "    del _d, _f\n"
    "print(\"Architecture ready.\")",
    "cell-arch"))

# Cell 8 – training
cells.append(code(
    "dual_loader, _ = get_loader(DUAL_TRAIN_N, batch_size=BATCH, seed=42, split=\"train\")\n"
    "tloader,     _ = get_loader(N_TRANSFER, seed=1)\n"
    "\n"
    "optimiser = torch.optim.Adam(\n"
    "    list(ml_adapters.parameters()) + list(lang_text_proj.parameters()),\n"
    "    lr=DUAL_LR\n"
    ")\n"
    "\n"
    "# Cache frozen XLM-R backbone features for all class prompts (computed once).\n"
    "# Only lang_text_proj changes during training; txt_backbone stays fixed.\n"
    "print(\"Caching frozen XLM-R backbone text features...\")\n"
    "with torch.no_grad():\n"
    "    txt_backbone = {}\n"
    "    for lang in LANGS:\n"
    "        prompts = [TEMPLATES[lang].format(TRANSLATIONS[c][lang]) for c in CLASSES]\n"
    "        tokens = tokenizer(prompts).to(device)\n"
    "        attn_mask = (tokens != model.text.config.pad_token_id).long()\n"
    "        out = model.text.transformer(input_ids=tokens, attention_mask=attn_mask)\n"
    "        masked = out.last_hidden_state * attn_mask.unsqueeze(-1).float()\n"
    "        pooled = masked.sum(dim=1) / attn_mask.sum(-1, keepdim=True).float()\n"
    "        txt_backbone[lang] = pooled.detach()  # [10, 768] -- static throughout training\n"
    "print(\"Done.\")\n"
    "\n"
    "# PGD against EN pair. txt_en must be detached so pixel gradient is isolated\n"
    "# from lang_text_proj parameters during PGD steps.\n"
    "def pgd_dual_en(x, y, txt_en, eps=DUAL_TRAIN_EPS, steps=DUAL_PGD_STEPS):\n"
    "    x0 = x.clone().detach()\n"
    "    alpha = 2.5 * eps / steps\n"
    "    xadv = torch.clamp(x0 + torch.empty_like(x0).uniform_(-eps, eps), 0, 1).detach()\n"
    "    for _ in range(steps):\n"
    "        xadv.requires_grad_(True)\n"
    "        feat = encode_image_ml(xadv, \"en\")\n"
    "        loss = F.cross_entropy(logits_for(feat, txt_en), y)\n"
    "        g = torch.autograd.grad(loss, xadv)[0]\n"
    "        with torch.no_grad():\n"
    "            xadv = torch.min(torch.max(xadv + alpha * g.sign(), x0 - eps), x0 + eps)\n"
    "            xadv = torch.clamp(xadv, 0, 1)\n"
    "        xadv = xadv.detach()\n"
    "    return xadv\n"
    "\n"
    "loss_hist = {\"ce\": [], \"div\": [], \"ret\": []}\n"
    "t0 = time.time()\n"
    "for epoch in range(DUAL_EPOCHS):\n"
    "    ep_ce, ep_div, ep_ret, n_batches = 0., 0., 0., 0\n"
    "\n"
    "    for xb, yb in dual_loader:\n"
    "        xb, yb = xb.to(device), yb.to(device)\n"
    "\n"
    "        # Current text embeddings — grad flows through lang_text_proj\n"
    "        txt_live = {\n"
    "            lang: F.normalize(lang_text_proj[lang](txt_backbone[lang]), dim=-1)\n"
    "            for lang in LANGS\n"
    "        }\n"
    "\n"
    "        # PGD vs EN pair — detach txt_en so PGD gradient only touches pixels\n"
    "        xb_adv = pgd_dual_en(xb, yb, txt_live[\"en\"].detach())\n"
    "\n"
    "        optimiser.zero_grad()\n"
    "\n"
    "        # Image features for all languages on clean batch\n"
    "        img_feats = {lang: encode_image_ml(xb, lang) for lang in LANGS}\n"
    "\n"
    "        # (1) Classification: sum_l CE(f_l(x) . g_l^T, y)\n"
    "        loss_ce = sum(\n"
    "            F.cross_entropy(logits_for(img_feats[lang], txt_live[lang]), yb)\n"
    "            for lang in LANGS\n"
    "        ) / len(LANGS)\n"
    "\n"
    "        # (2) Image divergence: sum_{l!=l'} cos(z_l, z_l')\n"
    "        orth, n_pairs = 0., 0\n"
    "        lang_list = list(img_feats)\n"
    "        for i in range(len(lang_list)):\n"
    "            for j in range(i + 1, len(lang_list)):\n"
    "                orth += (img_feats[lang_list[i]] * img_feats[lang_list[j]]).sum(dim=-1).mean()\n"
    "                n_pairs += 1\n"
    "        loss_div = orth / n_pairs\n"
    "\n"
    "        # (3) Adversarial retention: sum_{l!=en} CE(f_l(x_adv) . g_l^T, y)\n"
    "        # xb_adv is detached; gradient flows through non-EN adapters + text heads\n"
    "        loss_ret = sum(\n"
    "            F.cross_entropy(logits_for(encode_image_ml(xb_adv, lang), txt_live[lang]), yb)\n"
    "            for lang in LANGS if lang != \"en\"\n"
    "        ) / (len(LANGS) - 1)\n"
    "\n"
    "        loss = loss_ce + LAM_DIV * loss_div + LAM_RET * loss_ret\n"
    "        loss.backward()\n"
    "        optimiser.step()\n"
    "\n"
    "        ep_ce  += loss_ce.item()\n"
    "        ep_div += loss_div.item()\n"
    "        ep_ret += loss_ret.item()\n"
    "        n_batches += 1\n"
    "\n"
    "    loss_hist[\"ce\"].append(ep_ce / n_batches)\n"
    "    loss_hist[\"div\"].append(ep_div / n_batches)\n"
    "    loss_hist[\"ret\"].append(ep_ret / n_batches)\n"
    "    print(f\"Epoch {epoch+1:>2}/{DUAL_EPOCHS}  \"\n"
    "          f\"ce={ep_ce/n_batches:.3f}  \"\n"
    "          f\"div={ep_div/n_batches:.3f}  \"\n"
    "          f\"ret={ep_ret/n_batches:.3f}  \"\n"
    "          f\"({time.time()-t0:.0f}s)\")\n"
    "\n"
    "print(f\"\\nTraining complete in {time.time()-t0:.0f}s\")",
    "cell-train"))

# Cell 9 – clean accuracy + loss curves
cells.append(code(
    "fig, axes = plt.subplots(1, 2, figsize=(13, 3))\n"
    "\n"
    "ep_ax = range(1, DUAL_EPOCHS + 1)\n"
    "axes[0].plot(ep_ax, loss_hist[\"ce\"],  label=\"CE (classification)\")\n"
    "axes[0].plot(ep_ax, loss_hist[\"div\"], label=\"image divergence (lam=1.0)\")\n"
    "axes[0].plot(ep_ax, loss_hist[\"ret\"], label=\"retention (lam=1.0)\")\n"
    "axes[0].set_xlabel(\"Epoch\"); axes[0].set_ylabel(\"Loss component\")\n"
    "axes[0].set_title(\"Training loss components\")\n"
    "axes[0].legend(); axes[0].grid(True, alpha=0.3)\n"
    "\n"
    "ldr500c, _ = get_loader(N_CLEAN, seed=0)\n"
    "preds_clean = {l: [] for l in LANGS}\n"
    "lbls_clean  = []\n"
    "with torch.no_grad():\n"
    "    TXT_LANG = build_txt_lang()\n"
    "    for xb, yb in ldr500c:\n"
    "        xb = xb.to(device)\n"
    "        for lang in LANGS:\n"
    "            p = torch.softmax(logits_for(encode_image_ml(xb, lang), TXT_LANG[lang]), dim=-1)\n"
    "            preds_clean[lang].append(p.cpu().numpy())\n"
    "        lbls_clean.append(yb.numpy())\n"
    "\n"
    "preds_clean = {l: np.concatenate(preds_clean[l]) for l in LANGS}\n"
    "lbls_clean  = np.concatenate(lbls_clean)\n"
    "\n"
    "print(\"Clean accuracy (dual-encoder pairs, n=500):\")\n"
    "accs = {}\n"
    "for lang in LANGS:\n"
    "    acc = (np.argmax(preds_clean[lang], 1) == lbls_clean).mean()\n"
    "    accs[lang] = acc\n"
    "    print(f\"  {lang}: {acc*100:.1f}%\")\n"
    "\n"
    "axes[1].bar(LANGS, [accs[l]*100 for l in LANGS])\n"
    "axes[1].axhline(90, color=\"green\", linestyle=\"--\", linewidth=1, label=\"90%\")\n"
    "axes[1].set_ylabel(\"Clean accuracy (%)\")\n"
    "axes[1].set_title(\"Clean accuracy by language\")\n"
    "axes[1].legend(); axes[1].grid(True, alpha=0.3, axis=\"y\")\n"
    "plt.tight_layout(); plt.show()",
    "cell-clean"))

# Cell 10 – retention table
cells.append(code(
    "# Pre-compute clean predictions on tloader (300 samples)\n"
    "clean_probs_dual = {l: [] for l in LANGS}\n"
    "_lbls_dual = []\n"
    "with torch.no_grad():\n"
    "    TXT_LANG = build_txt_lang()\n"
    "    for xb, yb in tloader:\n"
    "        xb = xb.to(device)\n"
    "        for lang in LANGS:\n"
    "            p = torch.softmax(logits_for(encode_image_ml(xb, lang), TXT_LANG[lang]), dim=-1)\n"
    "            clean_probs_dual[lang].append(p.cpu().numpy())\n"
    "        _lbls_dual.append(yb.numpy())\n"
    "\n"
    "clean_probs_dual = {l: np.concatenate(clean_probs_dual[l]) for l in LANGS}\n"
    "_lbls_dual       = np.concatenate(_lbls_dual)\n"
    "\n"
    "# Eval PGD with PGD_STEPS=20 (stricter than training) against EN pair\n"
    "def pgd_eval_en(x, y, txt_en, eps, steps=PGD_STEPS):\n"
    "    x0 = x.clone().detach()\n"
    "    alpha = 2.5 * eps / steps\n"
    "    xadv = torch.clamp(x0 + torch.empty_like(x0).uniform_(-eps, eps), 0, 1).detach()\n"
    "    for _ in range(steps):\n"
    "        xadv.requires_grad_(True)\n"
    "        feat = encode_image_ml(xadv, \"en\")\n"
    "        loss = F.cross_entropy(logits_for(feat, txt_en), y)\n"
    "        g = torch.autograd.grad(loss, xadv)[0]\n"
    "        with torch.no_grad():\n"
    "            xadv = torch.min(torch.max(xadv + alpha * g.sign(), x0 - eps), x0 + eps)\n"
    "            xadv = torch.clamp(xadv, 0, 1)\n"
    "        xadv = xadv.detach()\n"
    "    return xadv\n"
    "\n"
    "print(\"Retention -- dual encoder pairs, PGD vs EN pair (20 steps):\")\n"
    "print(f\"{'eps':>5} | EN fooled | {'ko':>8} | {'es':>8} | {'fr':>8} | {'ja':>8}\")\n"
    "print(\"-\" * 57)\n"
    "\n"
    "adv_probs_dual = {}\n"
    "for eps in EPS_LIST:\n"
    "    with torch.no_grad():\n"
    "        TXT_LANG = build_txt_lang()\n"
    "\n"
    "    ep_probs  = {l: [] for l in LANGS}\n"
    "    ep_labels = []\n"
    "    for xb, yb in tloader:\n"
    "        xb, yb = xb.to(device), yb.to(device)\n"
    "        xb_adv = pgd_eval_en(xb, yb, TXT_LANG[\"en\"], eps=eps / 255)\n"
    "        with torch.no_grad():\n"
    "            batch_p = {\n"
    "                lang: torch.softmax(\n"
    "                    logits_for(encode_image_ml(xb_adv, lang), TXT_LANG[lang]), dim=-1\n"
    "                ).cpu().numpy()\n"
    "                for lang in LANGS\n"
    "            }\n"
    "        for lang in LANGS:\n"
    "            ep_probs[lang].append(batch_p[lang])\n"
    "        ep_labels.append(yb.cpu().numpy())\n"
    "\n"
    "    adv_probs_dual[eps] = {l: np.concatenate(ep_probs[l]) for l in LANGS}\n"
    "    lbl_t = np.concatenate(ep_labels)\n"
    "\n"
    "    en_clean_ok  = np.argmax(clean_probs_dual[\"en\"], 1) == lbl_t\n"
    "    en_adv_wrong = np.argmax(adv_probs_dual[eps][\"en\"], 1) != lbl_t\n"
    "    fooled = en_clean_ok & en_adv_wrong\n"
    "    n_fooled = int(fooled.sum())\n"
    "    if n_fooled == 0:\n"
    "        print(f\"{eps:>5} | {n_fooled:>9} | {'n/a':>8} | {'n/a':>8} | {'n/a':>8} | {'n/a':>8}\")\n"
    "        continue\n"
    "    ret = {l: (np.argmax(adv_probs_dual[eps][l][fooled], 1) == lbl_t[fooled]).mean()\n"
    "           for l in [\"ko\", \"es\", \"fr\", \"ja\"]}\n"
    "    print(f\"{eps:>5} | {n_fooled:>9} | \" +\n"
    "          \" | \".join(f\"{ret[l]*100:>7.1f}%\" for l in [\"ko\", \"es\", \"fr\", \"ja\"]))\n"
    "\n"
    "print()\n"
    "print(\"For reference -- KO retention at eps=8 in prior experiments:\")\n"
    "print(\"  No defence (baseline):    ~86%  (full transfer)\")\n"
    "print(\"  Rank-8 out-proj LoRA:       8.7%\")\n"
    "print(\"  TXT_ORTH isolated:         12.5%\")\n"
    "print(\"  Rank-64 out-proj LoRA:     29.0%  (previous best)\")\n"
    "print(\"  Multi-layer LoRA r16:       0%   (training collapsed, wrong tensor layout)\")\n"
    "print(\"  Per-language ViT 5 ep:      0%   (undertrained)\")\n"
    "print(\"  Target:                   >50%\")",
    "cell-retention"))

# Cell 11 – verdict
cells.append(md(
    "### Verdict -- Dual language-specific encoder pairs (LoRA r32 + text heads, 15 epochs)\n"
    "\n"
    "**Setup:** 60 `IntermediateLoRA` adapters (rank-32, all 12 ViT blocks, correct NLD layout)\n"
    "+ 5 language text projection heads (`nn.Linear(768, 512, bias=False)`).\n"
    "Total trainable: ~2.8M params. Frozen backbone: 87.8M.\n"
    "Three-term loss: CE + image divergence (lam=1.0) + adversarial retention (lam=1.0).\n"
    "LR=1e-4, 15 epochs, training eps=2/255, BATCH=64.\n"
    "\n"
    "**Architecture fixes vs. prior experiments:**\n"
    "- Correct NLD [batch, seq, d] layout via `vit._embeds()` (Exp C used LND: wrong attention)\n"
    "- Language-specific text heads (Exps A/B/C used shared text; losses fought each other)\n"
    "- LoRA injected at all 12 ViT blocks (Exp C only used 4)\n"
    "\n"
    "*(fill in after running)*\n"
    "\n"
    "| eps | EN fooled | KO | ES | FR | JA |\n"
    "|---|---|---|---|---|---|\n"
    "| 0.5 | -- | -- | -- | -- | -- |\n"
    "| 1   | -- | -- | -- | -- | -- |\n"
    "| 2   | -- | -- | -- | -- | -- |\n"
    "| 4   | -- | -- | -- | -- | -- |\n"
    "| 8   | -- | -- | -- | -- | -- |\n"
    "\n"
    "**Interpretation:** *(fill in after running)*",
    "cell-verdict"))

# Build and save
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "2026summer",
            "language": "python",
            "name": "2026summer"
        },
        "language_info": {"name": "python", "version": "3.11.0"}
    },
    "cells": cells
}

out_path = r'd:\ian\2026summer\notebooks\dual_encoder_divergence.ipynb'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Saved {len(cells)} cells to {out_path}")
for i, c in enumerate(cells):
    src = c['source'] if isinstance(c['source'], str) else ''.join(c['source'])
    print(f"  [{i}] {c['cell_type']:8}: {src[:70].replace(chr(10),' ')}")
